# Generated by Django 3.0.1 on 2020-01-03 17:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohort', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('netid', models.CharField(blank=True, help_text='The Georgetown NetID of the faculty member', max_length=24, null=True)),
                ('prefix', models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dean', 'Dean'), ('Hon.', 'Hon.'), ('Rev.', 'Rev.')], default=None, help_text="Title or prefix for the faculty member's display name", max_length=4, null=True)),
                ('first_name', models.CharField(blank=True, help_text='The first name of the faculty, if not set the user is used', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, help_text='The last name of the faculty, if not set the user is used', max_length=255, null=True)),
                ('suffix', models.CharField(blank=True, choices=[('PhD', 'PhD'), ('Esq', 'Esq'), ('MD', 'MD'), ('LLD', 'LLD'), ('JD', 'JD'), ('RN', 'RN'), ('DO', 'DO'), ('DDS', 'DDS'), ('CPA', 'CPA'), ('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], default=None, help_text="Suffix for the faculty member's display name", max_length=4, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Expected hourly rate of faculty, used for contract validation', max_digits=10, null=True)),
                ('user', models.OneToOneField(blank=True, help_text='The user associated with the faculty member (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'faculty',
                'verbose_name_plural': 'faculty members',
                'db_table': 'faculty',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('role', models.CharField(blank=True, choices=[('IN', 'Instructor'), ('TA', 'Teaching Assistant'), ('CA', 'Capstone Advisor'), ('FD', 'Faculty Director'), ('SE', 'Subject Matter Expert')], default='IN', help_text='The role of the faculty member in the cohort', max_length=2)),
                ('start', models.DateField(blank=True, default=None, help_text='The start date of the assignment (defaults to course/cohort start)', null=True)),
                ('end', models.DateField(blank=True, default=None, help_text='The end date of the assignment (defaults to course/cohort end)', null=True)),
                ('hours', models.PositiveSmallIntegerField(blank=True, default=None, help_text='The number of instructional hours assigned to the advisor (defaults to course hours)', null=True)),
                ('effort', models.PositiveSmallIntegerField(blank=True, default=100, help_text='Percent of effort/responsibility the instructor is assigned', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('primary', models.BooleanField(default=True, help_text='If this instructor has primary responsibility for the course or advisor role')),
                ('cohort', models.ForeignKey(blank=True, help_text='Must specify if a course is not set, otherwise will default to course cohort', on_delete=django.db.models.deletion.CASCADE, related_name='instructional_assignments', to='cohort.Cohort')),
                ('course', models.ForeignKey(blank=True, default=None, help_text='If the role is instructor, specify the course the faculty is teaching', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructional_assignments', to='cohort.Course')),
                ('faculty', models.ForeignKey(help_text='Faculty member who is instructing a course or advising the cohort', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='faculty.Faculty')),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ('-start', '-cohort__cohort'),
                'unique_together': {('faculty', 'cohort', 'course', 'role')},
            },
        ),
    ]
