# Generated by Django 3.0.4 on 2020-03-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='bio',
            field=models.CharField(blank=True, help_text='Short bio describing your data science activities', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(blank=True, help_text='Preferred contact email for faculty and students', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='exclude',
            field=models.BooleanField(default=False, help_text='Exclude from active faculty participation (archive only)'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='github',
            field=models.CharField(blank=True, help_text='Optional GitHub username (no url or @ symbol prefix)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Optional URL of your LinkedIn profile', null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='occupation',
            field=models.CharField(blank=True, help_text='Title or role of your non-Georgetown related occupation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='organization',
            field=models.CharField(blank=True, help_text='The organization you work for outside of Georgetown', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='twitter',
            field=models.CharField(blank=True, help_text='Optional Twitter username (no url or @ symbol prefix)', max_length=100, null=True),
        ),
    ]
