# Generated by Django 3.0.1 on 2019-12-30 22:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='faculty',
            field=models.ForeignKey(help_text='The faculty member that is advising the cohort', on_delete=django.db.models.deletion.CASCADE, related_name='advisor_assignments', to='faculty.Faculty'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveSmallIntegerField(help_text='The primary key of the assignment object.')),
                ('content_type', models.ForeignKey(help_text='The model type of the assignment object, e.g. Instructor or Assignment', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ('-created',),
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
