# Generated by Django 3.0.1 on 2019-12-30 23:20

from django.db import migrations


def connect_generic_assignments(apps, schema_editor):
    """
    Save all of the instructor and advisor assignments to ensure a generic assignment
    is created and so that the modified timestamp is updated to the time of the migration.
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Assignment = apps.get_model('faculty', 'Assignment')

    for model in ("Instructor", "Advisor"):
        Model = apps.get_model('faculty', model)
        for obj in Model.objects.all():
            content_type = ContentType.objects.get_for_model(obj)
            Assignment.objects.create(
                content_type=content_type, object_id=obj.id,
                created=obj.created, modified=obj.modified,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_generic_assignments'),
    ]

    operations = [
        migrations.RunPython(connect_generic_assignments, migrations.RunPython.noop)
    ]
