# Generated by Django 3.0.4 on 2020-03-08 04:06

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_faculty_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(help_text='First name of the contact', max_length=80)),
                ('last_name', models.CharField(help_text='Last name of the contact', max_length=80)),
                ('email', models.EmailField(help_text='Email address of the contact', max_length=254, unique=True)),
                ('info', models.CharField(help_text="Describe contact's role and reasons for contacting them", max_length=500)),
                ('primary', models.BooleanField(default=False, help_text='A primary contact for the specified role, listed at top of page')),
                ('archive', models.BooleanField(default=False, help_text='Do not display the contact on any contact pages')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ('last_name',),
            },
        ),
    ]
