# Generated by Django 3.0.4 on 2020-03-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-zorder', 'last_name')},
        ),
        migrations.AddField(
            model_name='contact',
            name='zorder',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Specify the ordering of contacts, higher numbers appear earlier', null=True),
        ),
    ]
