# Generated by Django 3.1.3 on 2021-02-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0004_auto_20210204_1210'),
        ('faculty', '0005_contacts_zorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Must specify if a course is not set, otherwise will default to course cohort', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructional_assignments', to='cohort.cohort'),
        ),
    ]
