# Generated by Django 3.0.1 on 2019-12-30 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohort', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='courses', through='faculty.Instructor', to='faculty.Faculty'),
        ),
        migrations.AddField(
            model_name='capstone',
            name='cohort',
            field=models.ForeignKey(help_text='The cohort the capstone was completed in', on_delete=django.db.models.deletion.CASCADE, related_name='capstones', to='cohort.Cohort'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_id', 'section')},
        ),
    ]
