# Generated by Django 3.1.3 on 2021-02-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0003_calendar_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='cohort',
            field=models.PositiveSmallIntegerField(help_text='The cohort number, e.g. cohort count from the start of the program', unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, choices=[('SP', 'Spring'), ('SU', 'Summer'), ('FA', 'Fall')], help_text='The academic semester the course is in (cohort semester by default)', max_length=2),
        ),
    ]
